repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - nextflow_schema.json
    - assets/multiqc_config.yml
  schema_lint: false
  schema_params: false
  schema_description: false

template:
  org: nf-core
  name: assemblers
  description: NF-core pipeline for ONT long-read asssembly
  author: Julie Zelaya
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - nf_schema
    - gpu
  is_nfcore: true
