repository_type: pipeline

nf_core_version: 3.5.1

lint:
  nextflow_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - nextflow_schema.json
  schema_lint: false
  schema_params: false
  schema_description: false

template:
  org: nf-core
  name: assemblers
  description: Nf-core pipeline for ONT long-read bacterial assemblers
  author: Julie Zelaya
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - nf_schema
    - gpu
  is_nfcore: true
